/**
 * Invoice generator tests
 * Tests for invoice generation and Firestore saving
 */

import { generateInvoice } from '../src/services/invoice-generator';
import type { InvoiceSession } from '../../../shared/types';

// Mock dependencies
const mockSet = jest.fn();
const mockDoc = jest.fn(() => ({
  set: mockSet,
}));
const mockCollection = jest.fn(() => ({
  doc: mockDoc,
}));

const mockBucket = jest.fn(() => ({
  file: jest.fn(() => ({
    save: jest.fn().mockResolvedValue(undefined),
    publicUrl: jest.fn(() => 'https://storage.googleapis.com/test-bucket/test.pdf'),
  })),
}));

const mockStorage = jest.fn(() => ({
  bucket: mockBucket,
}));

const mockGeneratePDF = jest.fn().mockResolvedValue(Buffer.from('fake-pdf-content'));
const mockGetNextInvoiceNumber = jest.fn().mockResolvedValue('202610');
const mockAppendGeneratedInvoiceRow = jest.fn().mockResolvedValue(undefined);

jest.mock('@google-cloud/firestore', () => {
  return {
    Firestore: jest.fn(() => ({
      collection: mockCollection,
    })),
    FieldValue: {
      serverTimestamp: jest.fn(() => new Date('2026-01-17')),
    },
    Timestamp: {
      fromDate: jest.fn((date) => date),
    },
  };
});

jest.mock('@google-cloud/storage', () => {
  return {
    Storage: jest.fn(() => mockStorage()),
  };
});

jest.mock('../src/services/invoice-generator/pdf.generator', () => ({
  generateInvoicePDFWithConfig: jest.fn(() => mockGeneratePDF()),
}));

jest.mock('../src/services/invoice-generator/counter.service', () => ({
  getNextInvoiceNumber: jest.fn(() => mockGetNextInvoiceNumber()),
}));

jest.mock('../src/services/invoice-generator/config.service', () => ({
  getBusinessConfig: jest.fn(),
  getLogoBase64: jest.fn(),
}));

jest.mock('../src/services/sheets.service', () => ({
  appendGeneratedInvoiceRow: jest.fn(() => mockAppendGeneratedInvoiceRow()),
}));

jest.mock('../src/config', () => ({
  getConfig: jest.fn(() => ({
    generatedInvoicesBucket: 'test-bucket',
  })),
}));

// Import the mocked modules to set up the mocks
import * as configService from '../src/services/invoice-generator/config.service';

describe('Invoice Generator', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    // Set up the mocks to return the mock values
    (configService.getBusinessConfig as jest.Mock).mockResolvedValue({
      business: {
        name: 'Test Business',
        address: '123 Test St',
        phone: '123-456-7890',
        taxId: '123456789',
        taxStatus: 'עוסק מורשה',
        email: 'test@example.com',
      },
      invoice: {
        footer: 'Thank you!',
        digitalSignatureText: 'Signed',
        generatedByText: 'Generated by',
      },
    });
    (configService.getLogoBase64 as jest.Mock).mockResolvedValue(null);
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  describe('generateInvoice', () => {
    const userId = 123456;
    const username = 'testuser';
    const chatId = 789012;

    const baseSession: InvoiceSession = {
      status: 'confirming',
      documentType: 'invoice',
      customerName: 'John Doe',
      description: 'Test invoice',
      amount: 1000,
      paymentMethod: 'מזומן',
      date: '2026-01-17',
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    it('should successfully generate invoice without customerTaxId', async () => {
      const session: InvoiceSession = {
        ...baseSession,
        // customerTaxId is undefined
      };

      const result = await generateInvoice(session, userId, username, chatId);

      expect(result.invoiceNumber).toBe('202610');
      expect(result.pdfBuffer).toBeInstanceOf(Buffer);
      expect(result.pdfUrl).toContain('storage.googleapis.com');

      // Verify Firestore save was called
      expect(mockCollection).toHaveBeenCalledWith('generated_invoices');
      expect(mockDoc).toHaveBeenCalledWith('202610');
      expect(mockSet).toHaveBeenCalled();

      // Verify customerTaxId is NOT in the Firestore record
      const firestoreRecord = mockSet.mock.calls[0][0];
      expect(firestoreRecord).not.toHaveProperty('customerTaxId');
      expect(firestoreRecord.customerName).toBe('John Doe');
      expect(firestoreRecord.amount).toBe(1000);
    });

    it('should successfully generate invoice with customerTaxId', async () => {
      const session: InvoiceSession = {
        ...baseSession,
        customerTaxId: '123456789',
      };

      const result = await generateInvoice(session, userId, username, chatId);

      expect(result.invoiceNumber).toBe('202610');
      expect(result.pdfBuffer).toBeInstanceOf(Buffer);

      // Verify Firestore save was called
      expect(mockSet).toHaveBeenCalled();

      // Verify customerTaxId IS in the Firestore record
      const firestoreRecord = mockSet.mock.calls[0][0];
      expect(firestoreRecord).toHaveProperty('customerTaxId');
      expect(firestoreRecord.customerTaxId).toBe('123456789');
    });

    it('should not include customerTaxId when explicitly undefined', async () => {
      const session: InvoiceSession = {
        ...baseSession,
        customerTaxId: undefined,
      };

      await generateInvoice(session, userId, username, chatId);

      // Verify customerTaxId is NOT in the Firestore record
      const firestoreRecord = mockSet.mock.calls[0][0];
      expect(firestoreRecord).not.toHaveProperty('customerTaxId');
    });

    it('should handle invoice_receipt document type', async () => {
      const session: InvoiceSession = {
        ...baseSession,
        documentType: 'invoice_receipt',
        customerTaxId: '987654321',
      };

      await generateInvoice(session, userId, username, chatId);

      const firestoreRecord = mockSet.mock.calls[0][0];
      expect(firestoreRecord.documentType).toBe('invoice_receipt');
      expect(firestoreRecord.customerTaxId).toBe('987654321');
    });

    it('should throw error when session is incomplete', async () => {
      const incompleteSession: InvoiceSession = {
        status: 'confirming',
        documentType: 'invoice',
        // Missing required fields
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      await expect(generateInvoice(incompleteSession, userId, username, chatId)).rejects.toThrow(
        'Invoice session is incomplete'
      );
    });
  });
});
